### PR TITLE
Don't discard RT Volume time stamps

### PR DESCRIPTION
**Pull request by goodboy**
Relates to #274.

Parse the millisecond time stamps received from `genericTick` `77` and `48` convert it to `float` seconds and save to a new attribute
`Ticker.last_fill_time`.

This field is absolutely essential for anykind of accurate charting on small time frames.

I'm not married to any particular name for this attribute, some alternatives:
- `last_clearing_time`
- `last_volume_time`
- `last_trade_time`

Note, I also dropped a duplicate code block for tick `77` which wasn't being executed ever due to the `elif`.

I would like to also add some basic tests for this and an example in the docs if that's ok @erdewit.

I was thinking that the example you provided in #262 using `asyncio.run()` would be a good start.

For testing I was thinking of starting a suite that can be run by anyone with a data subscription *locally*.
We could do something simple like add some more examples and [run them from `pytest`](https://github.com/goodboy/tractor/blob/master/tests/test_docs_examples.py) as well as include them using sphinx's [..literalinclude](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude) directive directly from the `examples/` directory into the documentation.
 
What do you think about working towards using a docker container (choose one from #261 ?) in CI to run tests on commits down the road?

TODO:
- [x] change name to `rtTime` as per @erdewit request and naming consistency
- [ ] doc string documentation at `IB.reqMktData` for ID=233
- [ ] make it a `datetime`. I'm personally really opposed to this.

### CODE REVIEW

**Comment by drusakov778** [comment]
hi @goodboy , thanks for PR

> I was thinking that the example you provided in #264 using asyncio.run() would be a good start.

I believe you meant to reference an example in #262 

tests and continuous integration via docker will also be of merit, imo.

One comment about the code & PR: I personally like snake_case variable naming, but it seems like the variable style chosen for this project is CamelCase, so it probably makes sense to keep it in the same style; and the same idea about extra spacing.

P.S. absolutely love the comments and direct references to IB API.

**Comment by goodboy** [comment]
>I believe you meant to reference an example in #262

Woops, yep you're definitely right. This is the example that @erdewit wrote:
```python
import asyncio

import ib_insync as ibi


class App:

    async def run(self):
        self.ib = ibi.IB()
        with await self.ib.connectAsync():
            contracts = await self.searchForContracts('SPY')
            for contract in contracts:
                self.ib.reqMktData(contract)

            async for tickers in self.ib.pendingTickersEvent:
                print(tickers)

    def stop(self):
        self.ib.disconnect()

    async def searchForContracts(self, pattern):
        descriptions = await self.ib.reqMatchingSymbolsAsync(pattern)
        tasks = [
            self.ib.reqContractDetailsAsync(descr.contract)
            for descr in descriptions]
        results = await asyncio.gather(*tasks)
        return [cd.contract for cds in results for cd in cds]


app = App()
try:
    asyncio.run(app.run())
except (KeyboardInterrupt, SystemExit):
    app.stop()
```

>tests and continuous integration via docker will also be of merit, imo.
:+1: 

> but it seems like the variable style chosen for this project is CamelCase, so it probably makes sense to keep it in the same style; and the same idea about extra spacing.

Yah, totally slipped my mind on that one. Do you have a preferred name btw?
Also, extra spacing you think is too much?

**Comment by goodboy** [comment]
Oh one other thing i was going to point out is that I actually don't understand *where* `Wrapper.tickString()` is invoked from.

I originally added a line to the `handlers` in `decoder.Decoder` (was expecting it be somewhere [here](https://github.com/erdewit/ib_insync/blob/master/ib_insync/decoder.py#L73)) but it didn't seem to be required and that routine is invoked regardless. 

That leads me to believe one of 2 things:
- the `46` `msgId` is already handling this case?
- something else is going on that I'm not following in the code

Also there's this `47` handler that points to [`Decoder.softDollarTiers()`](https://github.com/erdewit/ib_insync/blob/master/ib_insync/decoder.py#L579) but that also points to what seems to be a non-existent method of the same name on `Wrapper`?  I'm guessing it has to be the first case above otherwise I would expect an attr error here.

**Comment by erdewit** [comment]
I think it's a good idea to add this time to the Ticker, thanks for this and for clearing up the dead code. Could you rename the field to ``rtTime`` (to have symmetry with ``rtVolume``) and make it of type ``datetime`` (for consistency)? It could also be documented at ``IB.reqMktData`` for ID=233.

Note that this time is not the exchange time, @drusakov778 already linked to some threads about this:
https://groups.io/g/insync/topic/73333384 
https://groups.io/g/twsapi/topic/4048094
So the unknown origin of this time stamp makes it of doubtful usefulness.

**Comment by erdewit** [comment]
> For testing I was thinking of starting a suite that can be run by anyone with a data subscription _locally_.

A pytest suite would be most welcome. 

> What do you think about working towards using a docker container (choose one from #261 ?) in CI to run tests on commits down the road?

I'm not sure how that works security wise?

**Comment by goodboy** [comment]
>Could you rename the field to rtTime (to have symmetry with rtVolume)

Of course.

>and make it of type datetime (for consistency)?

:crying_cat_face: I was kind of hoping we could have this not be a `datetime`. 
Did you get a chance to read #272?
I personally am having trouble understanding why you would want to covert to `datetime` at all in this level in the code.

>It could also be documented at IB.reqMktData for ID=233.

Cool will add to the doc string.

>Note that this time is not the exchange time

I'm not sure I'm seeing any evidence in these linked threads that this is for sure **not** exchange time other then hearsay about some issue with IB tech support.

I will be comparing with my other broker feeds for detailed comparison and will report back.

>So the unknown origin of this time stamp makes it of doubtful usefulness.

I have to respectfully disagree. I've measured this value for a little bit now and it's clearly *closer to the exchange* then the local time which is much more useful at the least for measuring latency **and** aligning real-time data historically in a more accurate way (despite your claim it is not exchange time).

I'm actually surprised you find the `time.time()` or `dateime.now()` on `TickerData` useful at all?
What exactly is the usefulness of these time stamps beside internal time keeping in `ib_insync`?

**Comment by erdewit** [comment]
>  What exactly is the usefulness of these time stamps beside internal time keeping in `ib_insync`?

For backtesting. When playing back the data the arrival time is the only time that matters.

**Comment by goodboy** [comment]
>For backtesting. When playing back the data the arrival time is the only time that matters.

@erdewit maybe I'm missing something but, how is the time that data arrives over the TCP connection useful to a back-testing framework?

I would imagine "arrival time" is probably the time the back tester **itself receives the data** since it has no control over the latency between when `ib_insync` receives a TCP payload and when it sees the actual quote / order data.

In theory there should be a mostly ergodic (for practical purposes, constant) latency in the IB -> TCP -> ib_insync -> backtester pipeline.

>  When playing back the data the arrival time is the only time that matters.

When "playing back data" you only need time deltas; it shouldn't matter where the timestamps are taken in the "deterministic" pipeline.

**Comment by jkleckner** [comment]
> > What do you think about working towards using a docker container (choose one from #261 ?) in CI to run tests on commits down the road?
> 
> I'm not sure how that works security wise?

Take a look at the approach to secrets here: https://github.com/docker-tws/docker-tws

**Comment by goodboy** [comment]
@jkleckner nice. That looks promising.

There used to be trial accounts iirc that I thought you could use for this kind of thing even if just to get a sense for the API. I wonder if @erdewit (or someone else) could maybe get ahold of a such a *throw away* account for this purpose if the IB peeps know it will take tech support load off of them :wink:.

Another thing I've been interested in is running tws / gw inside docker all the time:
https://github.com/mviereck/x11docker

Cheers.

**Comment by goodboy** [comment]
@jkleckner lol, looking closer that user looks a little, sketch.
I would have imagined that url would have pointed to an org and the dockerfile is downloading a browser and TWS over http.

I would much rather see something pre-built from a known distribution.

**Comment by drusakov778** [comment]
> Also, extra spacing you think is too much?

I have a soft spot for this as well - the moment I am coming into a new code I like to beautify it to the style I am used to/I like the most... but I think we most appropriate things is to keep the uniform style across the project, which ultimately may mean less spacing etc. Probably not new spacing, unless it is in places where it has been missed in original code, just to match the rest of codebase.

**Comment by goodboy** [comment]
@drusakov778 it's funny, i've been told my code is too *dense* often so I've been trying to be more open minded about space.

I'm am rather indifferent, so whatever @erdewit prefers.

**Comment by jkleckner** [comment]
> looks a little, sketch

@goodboy That wasn't an endorsement per se.  The repo is quite new, only a few days old in fact.

But the method of using secrets management via docker or k8s is an interesting approach.

> something pre-built from a known distribution

Given the existence of supply-chain attacks for images, you are probably better off building it locally for something that is so sensitive.

**Comment by erdewit** [comment]
@goodboy were you able to reproduce Dmitry's findings regarding this time field?

https://groups.io/g/twsapi/topic/4048094

**Comment by goodboy** [comment]
Hey @erdewit, I'm working on it.

I want to compare at least 3 brokers and i'll be doing it by end of week.
I'll link to the issue I make with findings when complete :)

**Comment by goodboy** [comment]
So just a quick update I definitely **have not** found that

>I have noticed that the timestamp for realtime bars sometimes goes backwards. If you are using the timestamp for anything important (like building bars) you probably want to defend against these out of order ticks.

In the measurements I've taken (for weeks now) there is never a lead on the time RtVolume timestamp over the one on my client data daemon; i.e. latency is always measuring positive. In theory this could just be the *luck* of tws not screwing up time on linux?

Example screen shot here:
https://imgur.com/a/9hvaZZv

RE. this slew of graphs from [this forum post](https://groups.io/g/twsapi/message/36212):
https://imgur.com/a/XyzZa

I haven't seen any patterns like this at all.
In fact I'm seeing very reliable periodic clock drift patterns that can likely be auto-correlated out to get an average latency.

Do I think these are actual exchange time stamps, likely not, but they're still an indication of latency in terms of what TWS is recording.

I still have to compare against some other brokers feeds to see the latency with their time stamps. Further in theory I an actually look at open/close values of bars and/or time stamps on tick data to see how much of a difference there is.

I'm going to conduct a longer study of this in our repo however I still do thing this value should not be converted to a `datetime` and instead leave it up to the user how to process the data from IB.

**Comment by erdewit** [comment]
This PR is replaced with commit 9badbc80cf5ee1d14cdbdd1ecb239767d7ce2944

Here is a test script:

```python
import asyncio

import ib_insync as ibi


class App:

    async def run(self):
        self.ib = ibi.IB()
        with await self.ib.connectAsync():
            contracts = [
                ibi.Stock(symbol, 'SMART', 'USD')
                for symbol in ['AAPL', 'TSLA', 'AMD', 'INTC']]
            for contract in contracts:
                self.ib.reqMktData(contract, '233')

            async for tickers in self.ib.pendingTickersEvent:
                for ticker in tickers:
                    print(ticker.rtTime)

    def stop(self):
        self.ib.disconnect()


app = App()
try:
    asyncio.run(app.run())
except (KeyboardInterrupt, SystemExit):
    app.stop()
```

with some output:

```
2020-09-18 17:21:34.459000+00:00
2020-09-18 17:21:34.209000+00:00
2020-09-18 17:21:32.955000+00:00
2020-09-18 17:21:34.710000+00:00
2020-09-18 17:21:34.709000+00:00
2020-09-18 17:21:34.710000+00:00
2020-09-18 17:21:34.959000+00:00
2020-09-18 17:21:34.960000+00:00
2020-09-18 17:21:34.961000+00:00
2020-09-18 17:21:34.962000+00:00
2020-09-18 17:21:35.213000+00:00
2020-09-18 17:21:35.213000+00:00
2020-09-18 17:21:34.709000+00:00
2020-09-18 17:21:35.213000+00:00
2020-09-18 17:21:35.461000+00:00
2020-09-18 17:21:35.461000+00:00
2020-09-18 17:21:35.461000+00:00
2020-09-18 17:21:35.461000+00:00
2020-09-18 17:21:35.213000+00:00
2020-09-18 17:21:35.461000+00:00
2020-09-18 17:21:35.712000+00:00
2020-09-18 17:21:35.712000+00:00
2020-09-18 17:21:35.712000+00:00
2020-09-18 17:21:35.713000+00:00
2020-09-18 17:21:35.713000+00:00
2020-09-18 17:21:35.712000+00:00
2020-09-18 17:21:35.963000+00:00
2020-09-18 17:21:35.963000+00:00
2020-09-18 17:21:35.712000+00:00
2020-09-18 17:21:35.963000+00:00
2020-09-18 17:21:36.213000+00:00
2020-09-18 17:21:36.213000+00:00
2020-09-18 17:21:36.464000+00:00
2020-09-18 17:21:36.463000+00:00
2020-09-18 17:21:36.713000+00:00
2020-09-18 17:21:36.714000+00:00
2020-09-18 17:21:36.715000+00:00
2020-09-18 17:21:36.715000+00:00
2020-09-18 17:21:36.715000+00:00
2020-09-18 17:21:36.715000+00:00
2020-09-18 17:21:36.965000+00:00
2020-09-18 17:21:36.965000+00:00
2020-09-18 17:21:37.216000+00:00
2020-09-18 17:21:37.216000+00:00
2020-09-18 17:21:37.216000+00:00
```

Looks like pretty bogus timestamps to me but it's there for anyone to use.

**Pull request closed without merging**
