### PR TITLE
Bassem tests

### PR DESCRIPTION
**Pull request by bassemfg**

### CODE REVIEW

**Comment by erdewit** [comment]
Hi there,

It seems that this PR implements an influx database built on top of ib_insync, without any changes to ib_insync itself. My advice would be to create a dedicated project for your influx code and make use of ib_insync as a separate package - there's no need to copy ib_insync into your own project structure.

**Comment by goodboy** [comment]
@bassemfg link us to it as well :surfer:

**Comment by AWS-Bassem** [comment]
Sorry, I created this pull request by mistake. was just trying to update my own fork. Thanks for your feedback though!

**Comment by bassemfg** [comment]
Sorry, I created this pull request by mistake. was just trying to update my own fork. Thanks for your feedback though!

**Pull request closed without merging**
