### PR TITLE
Added completedOrderEvent.

### PR DESCRIPTION
**Pull request by rowrowrowrow**
Adding a completedOrderEvent to respond specifically to completed orders.

### CODE REVIEW

**Comment by erdewit** [comment]
It's not an event really. Events are occurrences that happen in real time. The completed orders are sent by IBKR as a result of the reqCompletedOrders request.

**Comment by rowrowrowrow** [comment]
What is the recommended way to separate completed/open trades? I was hoping to execute some function on just the completed orders returned from reqCompletedOrders.

**Comment by erdewit** [comment]
For example, filter ``ib.trades()`` on ``trade.isDone()``. Or call ``reqCompletedOrders``.

**Comment by rowrowrowrow** [comment]
I'd like to separate and respond to only the orders returned from reqCompletedOrders. Since IB makes this request on connect I didn't want to duplicate the request just to clearly separate completed from active orders. Does trade.isDone() separate orders returned from reqCompletedOrders and orders completed during a session?

**Pull request closed without merging**
