### PR TITLE
pylintrc added

### PR DESCRIPTION
**Pull request by evelynmitchell**
Doing some lint cleanup. This repository has a different naming style than pylint prefers, so I've turned that check off.

### CODE REVIEW

**Comment by evelynmitchell** [comment]
There are quite a few functions with missing docstrings. If it is a good idea  to add them, I'll do them all at once. Until  then, the check is disabled.

**Comment by evelynmitchell** [comment]
Turned off the check for too-many-arguments in function calls. This would be invasive to fix, and would need good test coverage  to refactor.

**Comment by evelynmitchell** [comment]
Turned off the check for too-many-statements in functions. This would be invasive to fix, and would need good test coverage to refactor.

**Comment by evelynmitchell** [comment]
Turned off the check for too-many-branches in functions. This would be invasive to fix, and would need good test coverage to refactor.

**Comment by evelynmitchell** [comment]
Turned off the check for too-many-local variables. This would be invasive to fix, and would need good test coverage to refactor.

**Comment by evelynmitchell** [comment]
Turned off the check for unused-arguments. This would be a simple fix, but I would like to have good test coverage to refactor.

**Comment by evelynmitchell** [comment]
The big set of patches which I will do in chunks, are related to logging-fstring-interpolation, which will speed up logging.

**Comment by erdewit** [comment]
I rather like the way it is right now though, with f-strings.

**Pull request closed without merging**
